name: 590-dino
channels:
  - defaults
dependencies:
  - blas=1.0=openblas
  - bottleneck=1.4.2=py314hdbb4bc7_1
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.4=hca03da5_0
  - expat=2.7.3=h982b769_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libmpdec=4.0.0=h80987f9_0
  - libopenblas=0.3.30=hf2bb037_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lz4-c=1.9.4=h313beb8_1
  - ncurses=6.5=hee39554_0
  - numexpr=2.14.1=py314h4402d01_0
  - numpy=2.3.4=py314hde9b8b7_0
  - numpy-base=2.3.4=py314hb4b2851_0
  - openssl=3.0.18=h9b4081a_0
  - pandas=2.3.3=py314heb7d0cc_1
  - pip=25.2=pyh0d26453_1
  - python=3.14.0=h1858270_101_cp314
  - python-dateutil=2.9.0post0=py314hca03da5_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.14=1_cp314
  - pytz=2025.2=py314hca03da5_0
  - readline=8.3=h0b18652_0
  - six=1.17.0=py314hca03da5_0
  - sqlite=3.50.2=h79febb2_1
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025b=h04d1e81_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
prefix: /Users/aidanbaydush/anaconda3/envs/590-dino
